#!/bin/bash

set -e

distri=`lsb_release -i | cut -f2 | tr '[:upper:]' '[:lower:]'`

if [ $(dpkg-query -W -f='${Status}' curl 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  echo "Installing curl...."
  sudo apt-get install curl
  fi

if [ $(dpkg-query -W -f='${Status}' puppet 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  echo "Installing puppet..."
  sudo apt-get install puppet
fi

wget -N -q https://raw.githubusercontent.com/cedricbrx/puppet/master/site-$distri.pp -O /etc/puppet/site-$distri.pp
if [ $? -ne 0 ]; then
	/usr/bin/logger -i "Puppet has no internet connection, exiting" -t "puppet-apply"
	exit 1
fi
#mkdir -p /etc/facter/facts.d/
wget -N -q https://raw.githubusercontent.com/cedricbrx/puppet/master/usr/lib/ruby/vendor_ruby/facter/brandenbourger.rb -O /usr/lib/ruby/vendor_ruby/facter/brandenbourger.rb
#wget -N -q https://raw.githubusercontent.com/cedricbrx/puppet/master/etc/facter.d/brandenbourger.sh -O /etc/facter.d/brandenbourger.sh
puppet apply /etc/puppet/site-$distri.pp
touch /etc/dconf/db/brandenbourger.d/locks
dconf update
if [ $? -eq 0 ]; then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-apply"
    exit 0
else
    /usr/bin/logger -i "Puppet has run into an error, please run Puppet manually" -t "puppet-apply"
    exit 1
fi
